### ISSUE TITLE
check if portable version of wis2-downloader-gui can be made that do not require admin issues

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#25]
Dave highlighted that to install wis2-downloader-gui the user might need elevation issues. Can we please check/ensure that the GUI can be installed without required elevated issues

**Comment by RoryPTB** [comment]
The portable versions are now released with the normal installers by GitHub Actions as of PR #49. Nonetheless, after checking, I can now confirm **they still pose the same admin issues** because the application is _not_ code-signed ([see here for more information](https://github.com/wmo-im/wis2-subscription-manager/issues/37#issuecomment-2185877500)). For the same reason as issue #37, I will close this issue as not planned.
